### ISSUE TITLE
Missing H in sparql endpoint URL in dataset description

### ISSUE THREAD

**Issue by MaillPierre** [Wimmics/CovidOnTheWeb#9]
In the CovidOnTheWeb SPARQL endpoint, in the `<http://ns.inria.fr/covid19/datagouvfr/graph>` graph, in the triple `<http://ns.inria.fr/covid19/datagouvfr/dataset> <http://rdfs.org/ns/void#sparqlEndpoint> <https://covidonteweb.inria.fr/sparql>` there is a "h" missing to the SPARQL endpoint URI to make it `<https://covidontheweb.inria.fr/sparql>`

Noticed by @Jendersen

**Comment by frmichel** [comment]
For repo https://github.com/frmichel/covid19-statsfr-rdf-dataset.

Thx for noticing! 
Fixed.
